# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_from_json <- function(json, simplify, fill_na) {
    .Call(`_RcppSimdJson_rcpp_from_json`, json, simplify, fill_na)
}

.validateJSON <- function(filename) {
    .Call(`_RcppSimdJson_validateJSON`, filename)
}

parseExample <- function() {
    invisible(.Call(`_RcppSimdJson_parseExample`))
}

.cppVersion <- function() {
    .Call(`_RcppSimdJson_cppVersion`)
}

.unsupportedArchitecture <- function() {
    .Call(`_RcppSimdJson_unsupportedArchitecture`)
}

