# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_get_json_length <- function(json) {
    .Call(`_RcppSimdJson_rcpp_get_json_length`, json)
}

rcpp_from_json <- function(json) {
    .Call(`_RcppSimdJson_rcpp_from_json`, json)
}

.validateJSON <- function(filename) {
    .Call(`_RcppSimdJson_validateJSON`, filename)
}

