on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: macOS-latest, r: 'release', args: "--no-manual"}
        # - { os: macOS-latest, r: 'dev', args: "--no-manual"}
        - { os: windows-latest, r: 'release', args: "--no-manual"}
        # - { os: windows-latest, r: 'dev', args: "--no-manual"}
        - { os: ubuntu-latest, r: 'release'}
        # - { os: ubuntu-latest, r: 'dev'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: true
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: System Dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
          
      - name: sessionInfo
        run: Rscript -e "sessionInfo()"

      - name: R Dependencies
        run: Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')"

      - name: R CMD check                                        # `error_on = 'warning'` when upstream simdjson ready
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', build_args = '--no-multiarch' error_on = 'error', check_dir = 'check')" 

